export interface Monologue {
  id: number;
  title: string;
  theme: string;
  points: string[];
}

export const MONOLOGUES: Monologue[] = [
  {"id": 1, "title": "MONOLOGUE 01", "theme": "your school", "points": ["what your typical school day is like;", "what your favourite subject is, and why;", "what you like most about your school;", "what your attitude to your school life is."]},
  {"id": 2, "title": "MONOLOGUE 02", "theme": "conflicts with your friends", "points": ["why teenagers can have a conflict with their friends;", "what you usually have conflicts with your friends about;", "how you usually make up with your friends;", "what your attitude to conflicts with your friends is."]},
  {"id": 3, "title": "MONOLOGUE 03", "theme": "your school holidays", "points": ["when you have school holidays;", "what school holidays you would make longer, and why;", "what you enjoy doing during your school holidays;", "what your attitude to school holidays is."]},
  {"id": 4, "title": "MONOLOGUE 04", "theme": "travelling", "points": ["why people like travelling in Russia;", "what means of transport is the most popular for travelling in Russia, and why;", "what places in Russia you would like to visit;", "what your attitude to travelling is."]},
  {"id": 9, "title": "MONOLOGUE 09", "theme": "family", "points": ["why family plays an important role in every person's life;", "what a typical Russian family is like;", "who you feel closest to in your family and why;", "what your attitude to having a big family is."]},
  {"id": 10, "title": "MONOLOGUE 10", "theme": "animals", "points": ["what wild animals live in your region;", "whether it is a good idea to keep a wild animal as a pet, and why;", "why people build zoos in cities and towns;", "what your attitude to zoos is."]},
  {"id": 11, "title": "MONOLOGUE 11", "theme": "your school", "points": ["what your typical school day is like;", "what subjects at school you find most useful for your future, and why;", "what you are going to do when you leave school;", "what your attitude to school life is."]},
  {"id": 12, "title": "MONOLOGUE 12", "theme": "school life", "points": ["what your weekday is like;", "what you like about your school most of all;", "whether you prefer classroom learning or online learning, and why;", "what your attitude to your school life is."]},
  {"id": 13, "title": "MONOLOGUE 13", "theme": "shopping", "points": ["why many people enjoy shopping;", "who you like shopping with and why;", "what you like and dislike shopping for;", "what your attitude to online shopping is."]},
  {"id": 14, "title": "MONOLOGUE 14", "theme": "sports", "points": ["why a lot of young people do sports nowadays;", "what sports clubs and teams there are in your school;", "what you do to keep fit;", "what your attitude to doing sports activities is."]},
  {"id": 15, "title": "MONOLOGUE 15", "theme": "environmental problems", "points": ["why people worry about environmental problems nowadays;", "what the most serious environmental problem in the place where you live is;", "what young people can do to improve the ecological situation;", "what your attitude to environmental problems is."]},
  {"id": 16, "title": "MONOLOGUE 16", "theme": "travelling", "points": ["why most people like travelling;", "which season is the best for travelling in your opinion;", "what means of transport is the best for travelling, and why;", "what your attitude to travelling is."]},
  {"id": 17, "title": "MONOLOGUE 17", "theme": "your school", "points": ["what you like about your school most of all;", "how many lessons a day you usually have;", "what school subjects you have chosen for your exams, and why;", "what your attitude to the number of subjects you have to learn is."]},
  {"id": 18, "title": "MONOLOGUE 18", "theme": "your free time", "points": ["whether you have a lot of free time, and why, or why not;", "what you enjoy doing in your free time;", "what your Sunday afternoons are like;", "what your attitude to planning your free time is."]},
  {"id": 19, "title": "MONOLOGUE 19", "theme": "films", "points": ["what kinds of films modern teenagers enjoy;", "where you prefer watching films: on TV, on the Internet or in the cinema, and why;", "what film you have seen recently, what it was about;", "what your attitude to watching films as a way to spend your free time is."]},
  {"id": 20, "title": "MONOLOGUE 20", "theme": "pocket money", "points": ["why it is important for a teenager to have pocket money;", "how much pocket money a week you usually get;", "what you spend your pocket money on and why;", "what your attitude to earning pocket money is."]},
  {"id": 21, "title": "MONOLOGUE 21", "theme": "school homework", "points": ["how long it takes you to do your homework;", "what subject you usually start with, and why;", "whether schoolchildren should be given more or less homework, and why;", "what your attitude to school homework is."]},
  {"id": 22, "title": "MONOLOGUE 22", "theme": "TV", "points": ["why people spend time watching TV;", "what most teenagers prefer: watching TV or browsing the Internet, and why;", "whether there is a TV programme you really like;", "what your attitude to watching TV as a way to spend your free time is."]},
  {"id": 23, "title": "MONOLOGUE 23", "theme": "TV", "points": ["whether watching TV is a popular pastime with teenagers, and why, or why not;", "how many hours a week you watch TV;", "what TV programme is the most popular within your family;", "what your attitude to TV is."]},
  {"id": 24, "title": "MONOLOGUE 24", "theme": "your school", "points": ["what you like most about your school;", "what weekday you find the most difficult, and why;", "what you would like to change in your school life;", "what your attitude to your school life is."]},
  {"id": 25, "title": "MONOLOGUE 25", "theme": "learning foreign languages", "points": ["why lots of people learn foreign languages nowadays;", "why you have chosen to do the English exam this year;", "what you did to prepare for your English exam;", "what your attitude to learning foreign languages is."]},
  {"id": 26, "title": "MONOLOGUE 26", "theme": "keeping fit", "points": ["why a healthy lifestyle is popular nowadays;", "what you do to keep fit;", "what sports activities are popular with teenagers in your region;", "what your attitude to a healthy lifestyle is."]},
  {"id": 27, "title": "MONOLOGUE 27", "theme": "the Internet", "points": ["why today's teenagers use the Internet so much;", "how the Internet makes long-distance communication easier;", "what dangers teenagers can face when they use the Internet;", "what your attitude to the Internet is."]},
  {"id": 28, "title": "MONOLOGUE 28", "theme": "your best friend", "points": ["what people need friends for;", "how long you and your friend have known each other;", "what you enjoy doing together;", "what your attitude to friendship is."]},
  {"id": 29, "title": "MONOLOGUE 29", "theme": "the place where you live", "points": ["what your city, town or village is famous for;", "what your favourite place in your city, town or village is, and why you like it;", "whether you are going to stay in your city, town or village after leaving school or move to another place, and why;", "what your attitude to your city, town or village is."]},
  {"id": 30, "title": "MONOLOGUE 30", "theme": "household chores", "points": ["why it is important to share the household chores in a family;", "how household chores are divided in your family;", "what household chores you like and dislike doing and why;", "what your attitude to ignoring household chores is."]}
];
